fixed 2 things
asdfzxcvbn/pyzule-gen pull request #1
Opened 2024-04-11 09:29 UTC by binnichtaktiv

2024-04-11 10:26 UTC, binnichtaktiv commented
nvm it should work im lost as always

2024-04-11 13:03 UTC, asdfzxcvbn reviewed
pls

2024-04-11 13:03 UTC, asdfzxcvbn commented on install-pyzule-gen.sh
> +    echo "[*] ${PZ_DIR} does not exist. Creating..."
be consistent with style, everything shown to the user is shown in **lowercase** unless it's something case-sensitive

2024-04-11 13:03 UTC, asdfzxcvbn commented on install-pyzule-gen.sh
> +    python3 -m venv "${PZ_DIR}/venv"
don't hardcode `python3`, use something like https://github.com/asdfzxcvbn/pyzule/blob/2e4e024b3063c161194a581bfdd5354faf338433/install-pyzule.sh#L16 instead

2024-04-11 13:03 UTC, asdfzxcvbn commented on install-pyzule-gen.sh
> +echo "[*] pyzule-gen is ready to use!"
unnecessary comment

2024-04-11 13:03 UTC, asdfzxcvbn commented on pyzule-gen-ish.py
> +        f.write(json.dumps(used).encode('utf-8'))
be consistent with the rest of the quotes, switch the single quotes to double quotes

2024-04-11 13:14 UTC, asdfzxcvbn requested changes
needs

2024-04-12 06:30 UTC, binnichtaktiv reviewed
w

2024-04-12 14:28 UTC, closed without merging